version: 2.1

executors:
  pulumi:
    docker:
      - image: node:18.2.0

jobs:
  make:
    resource_class: xlarge
    executor: pulumi
    parameters:
      env:
        description: stage or prod
        type: string
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install dependencies
          command: npm i
      - run:
          command: "make"
      - run:
          name: Bump version and publish on master branch
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              make bump
              make publish
            fi

workflows:
  version: 2.1
  build:
    jobs:
      - make:
          name: make
          env: prod
