version: 2.1

executors:
  pulumi:
    docker:
      - image: node:18.2.0

jobs:
  make:
    resource_class: xlarge
    executor: pulumi
    parameters:
      env:
        description: stage or prod
        type: string
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: "make && make bump && make publish"

workflows:
  version: 2.1
  build-master:
    jobs:
      - make:
          name: make
          env: prod
          filters:
            branches:
              only: master
